### ISSUE TITLE
Downloading database 2022 - 4th quarter. Internet use

### ISSUE THREAD

**Issue by JisellArias** [Gabriel-Assuncao/PNADcIBGE#20]
Hello there,

I am writing from Colombia and need your help. I require the most recent individual-level database for people who use the internet. I've been attempting to download it using the R library, but the file size is too large, and it haven't been successful, even when selecting the specific variables I need.

I know that the total population using the internet is 161,627 thousand people over 10 years old. However, I need the microdata to analyze different ages, genders, socio-economic levels, and city/region.

Here is the script I am using:

_library(PNADcIBGE)
DatosPNADc <- get_pnadc(year=2022, topic=4, vars=c("S07001"), design=FALSE)_

And the error message R returns:

_probando la URL 'https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Anual/Microdados/Trimestre/Trimestre_4/Dados/PNADC_2022_trimestre4_20240425.zip'
Content type 'application/zip' length 237737407 bytes (226.7 MB)
downloaded 226.7 MB

probando la URL 'https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Anual/Microdados/Trimestre/Trimestre_4/Documentacao/input_PNADC_trimestre4_20240425.txt'
Content type 'text/plain; charset=UTF-8' length 86298 bytes (84 KB)
downloaded 84 KB

Error: std::bad_alloc_

Thanks in advance for your support.

**Comment by Gabriel-Assuncao** [comment]
Hi @JisellArias.

Unfortunately, some users are having problems obtaining certain microdata from PNADC. This occurs during the microdata preparation stage, that is, when cutting the position of each variable in the TXT file related to the microdata, as during this process the R software uses directly from the computer's RAM memory and often the computer's RAM memory is not enough to carry out such a process, in some cases more than 8GB of RAM memory is needed.

A possible solution to this problem is not to directly use the get_pnadc function from the PNADcIBGE package that reads online and instead download the microdata directly from the IBGE server through the link: [https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Anual/Microdados/Trimestre/Trimestre_4/](https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Anual/Microdados/Trimestre/Trimestre_4/) and then use the read_pnadc, pnadc_labeller, pnadc_deflator and pnadc_design also from the PNADcIBGE package for offline reading.

Another important tip is to avoid leaving other software open during the execution of the routine that can 'compete' for RAM memory with the R software, such as internet browsers, so the ideal is to close these software temporarily and after the process is complete to obtain the microdata, open it again.

For now I will close this issue and I kindly request that any other problems or questions that arise please contact me directly through the support channel: [pacotesipd@ibge.gov.br](pacotesipd@ibge.gov.br).

**Comment by JisellArias** [comment]
Could you please help me indicating how to do the offline read? and how to insert the labels and organized the database? thanks in advance.

**Comment by Gabriel-Assuncao** [comment]
Hi @JisellArias.

Firstly, you need to download the desired microdata through the link below and save it in the directory of your choice:
[https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Anual/Microdados/Trimestre/Trimestre_4/Dados/PNADC_2022_trimestre4_20240425.zip](https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Anual/Microdados/Trimestre/Trimestre_4/Dados/PNADC_2022_trimestre4_20240425.zip)

After that, it is necessary to download the INPUT file that will be used to structure this microdata, this file must be obtained through the link below and saved in the same directory as before:
[https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Anual/Microdados/Trimestre/Trimestre_4/Documentacao/input_PNADC_trimestre4_20240425.txt](https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Anual/Microdados/Trimestre/Trimestre_4/Documentacao/input_PNADC_trimestre4_20240425.txt)

So now it is necessary to use the read_pnadc function from the PNADcIBGE package providing as a value for the microdata argument the path of the directory where the microdata were saved indicating the name of the reference file which must be in TXT format, that is, it must have been extracted from the file ZIP. Furthermore, in this same function it is necessary to provide the input_txt argument with the directory path and the name of the INPUT file in TXT format that was previously downloaded. If you are interested, you can also provide a vector of variables in the vars argument to cut the microdata with only these variables and those necessary to incorporate the sampling design.

If you are interested in labeling the categorical variables of the microdata, then you need to download the research dictionary through the link below, saving it in the same directory as before:
[https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Anual/Microdados/Trimestre/Trimestre_4/Documentacao/dicionario_PNADC_microdados_trimestre4_20240425.xls](https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Anual/Microdados/Trimestre/Trimestre_4/Documentacao/dicionario_PNADC_microdados_trimestre4_20240425.xls)

And then use the pnadc_labeller function from the PNADcIBGE package, providing the data_pnadc argument with the name of the object where the process used in the read_pnadc function was saved and for the dictionary.file argument, you must provide the directory path and the name of the file in XLS format referring to the research dictionary.

If you are also interested in inserting deflation indices to transform income variables from nominal to real values, you must download the desired deflator file, below we are providing the link to the most recent year available, in case of 2023, and save in the same directory as before:
[https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Anual/Microdados/Trimestre/Trimestre_4/Documentacao/deflator_PNADC_2023_trimestre4.xls](https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Anual/Microdados/Trimestre/Trimestre_4/Documentacao/deflator_PNADC_2023_trimestre4.xls)

And then use the pnadc_deflator function from the PNADcIBGE package, providing the data_pnadc argument with the name of the object where the process used in the read_pnadc and pnadc_labeller functions was saved and for the deflator.file argument, you must provide the directory path and the name of the file in XLS format referring to the research deflator.

And finally, the pnadc_design function from the PNADcIBGE package must be used to incorporate the sample design, a fundamental step in this process and when using this function, simply supply the data_pnadc argument with the name of the object used in the read_pnadc, pnadc_labeller and pnadc_deflator functions of the mentioned steps previously. And then just use the functions of the survey package to obtain the desired estimates.

I believe this is it, so if you have any other questions or problems, please contact us via the customer service channel: [pacotesipd@ibge.gov.br](pacotesipd@ibge.gov.br).
