### ISSUE TITLE
Erro de leitura no arquivo ftp

### ISSUE THREAD

**Issue by rcleoni** [Gabriel-Assuncao/PNADcIBGE#9]
Error in utils::download.file(url = paste0(ftpdata, dataname), destfile = paste0(savedir, : 
cannot open URL 'ftp://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Anual/Microdados/Visita/Visita_5/Dados/PNADC_2021_visita5.zip'

**Comment by Gabriel-Assuncao** [comment]
Prezado Roberto Leoni, boa noite.
Recentemente os principais navegadores de internet pararam de fornecer suporte e acesso ao protocolo FTP e por isso o acesso aos microdados precisou ser alterado para o protocolo HTTPS na última versão do pacote PNADcIBGE, então solicito por gentileza que atualize o pacote através do comando install.packages("PNADcIBGE"), sendo que a versão do pacote deve ser igual ou superior à 0.7.0.
Pedimos para realizar o procedimento indicado acima que então será possível ter acesso aos microdados desejados, aproveito para solicitar por gentileza o fechamento desta issue, caso o problema seja de fato resolvido.
Sendo assim, agradeço imensamente pela atenção e me coloco à disposição para qualquer eventualidade.

Dear Roberto Leoni, good evening.
Recently the main internet browsers stopped providing support and access to the FTP protocol and therefore the access to microdata had to be changed to the HTTPS protocol in the latest version of the PNADcIBGE package, so I kindly request you to update the package through the command install.packages("PNADcIBGE"), and the package version must be equal to or greater than 0.7.0.
I ask you to carry out the procedure indicated above so that it will be possible to have access to the desired microdata, I would like to take this opportunity to kindly ask you to close this issue, if the problem is indeed resolved.
Therefore, I thank you immensely for your attention and I make myself available for any eventuality.

**Comment by rcleoni** [comment]
Obrigado pelo rápido retorno.
